## Bitnami Drupal image version
## ref: https://hub.docker.com/r/bitnami/drupal/tags/
##
image:
  registry: eu.gcr.io
  repository: php_repo
  tag: master
  appMode: prod
  pullSecrets:
     - regcred

drupalUsername: user
drupalEmail: user@example.com
allowEmptyPassword: "yes"

mariadb:
  enabled: true
  auth:
    database: niji_drupal
    username: niji_drupal
    password: niji_drupal

  architecture: standalone
  primary:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
    resources:
      requests:
        cpu: 500m
        memory: 512Mi

serviceType: ClusterIP

ingress:
  enabled: true
  # Used to create Ingress record (should used with ServiceType: ClusterIP).
  hostname: drupal.local
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/whitelist-source-range: '77.197.104.170/32,90.102.123.61/32,10.0.0.0/8,92.154.9.215/32,195.25.228.205/32,37.157.227.34/32,90.82.241.97/32,213.215.62.250/32,93.13.84.90/32,93.13.84.100/32,77.192.166.130/32'
    # 92.154.9.215/32 - IP Niji Gateway réseau fixe ILM
    # 90.102.123.61 - IP Niji Gateway réseau fixe Rennes (old)
    # 77.197.104.170 - IP Niji Gateway réseau fixe Rennes (new)
    # 195.25.228.205/32 - IP Niji Gateway réseau fixe Nantes
    # 93.13.84.100/32 - IP Niji Gateway réseau fixe Nantes (new)
    # 10.0.0.0/8 - IP Internal k8s
    # 37.157.227.34/32 - Niji VPN
    # 90.82.241.97 - IP Niji Gateway réseau fixe Lyon
    # 213.215.62.250/32 - Niji Bordeaux
    # 77.192.166.130/32 - Niji Bordeaux (new)
    # 93.13.84.90/32 - Niji Lille

persistence:
  enabled: true
  apache:
    accessMode: ReadWriteOnce
    size: 1Gi
  drupal:
    accessMode: ReadWriteOnce
    size: 8Gi

apache:
  enabled: false
  image:
    registry: eu.gcr.io
    repository: apache_repo
    tag: master
    pullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 512Mi

redis:
  enabled: true
  architecture: standalone
  cluster:
    enabled: false
  master:
    persistence:
      enabled: true
  auth:
    enabled: false

phpmyadmin:
  enabled: false
  db:
    port: 3306
    chartName: mariadb
  probesEnabled: false

varnish:
  enabled: false
  debug: true
  image:
    repository: wodby/drupal-varnish
    tag: 4.1-2.2.0
    pullPolicy: Always

mailhog:
  enabled: true

resources:
  requests:
    memory: 512Mi
    cpu: 300m

volumeMounts:
  drupal:
    mountPath: /niji/drupal
  apache:
    mountPath: /niji/apache

livenessProbe:
  tcpSocket:
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  tcpSocket:
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
