# Schema for the configuration files of the tuto_theme theme.
tuto_theme.settings:
  type: theme_settings
  label: 'tuto_theme settings'
  mapping:
    example:
      type: string
      label: Example
